sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot
before_cache:
  - rm -Rf $HOME/.boot/cache/tmp
install:
- wget -O boot https://github.com/boot-clj/boot-bin/releases/download/2.5.2/boot.sh
- chmod 755 boot
- ./boot -V
script: ./boot tests
